### PR TITLE
Up version, publish to maven-private

### PR DESCRIPTION
**Pull request by friedger**
Up version
Publish to maven-private repo via bintray

### CODE REVIEW

**Comment by stefanhoth** [comment]
:+1:

**Comment by blundell** [comment]
why did you decide to add novoda into the name? Should have been in the PR desc

**Comment by friedger** [comment]
@blundell This is the convention to track the version of the clones as described in https://github.com/novoda/base/wiki/Novoda-naming-conventions ;-)

**Comment by blundell** [comment]
screen shot 2015-07-06 at 11 56 37

**Pull request merged**
